### ISSUE TITLE
Debug-Option in Example Flow

### ISSUE THREAD

**Issue by littleyoda** [cinhcet/node-red-contrib-component-dashboard#1]
In your example Flow the option "debug window" in the debug-node is disabled.
Testing the flow, you don't receive any messages when you are clicking on the button.

Took me quite a long time to figure it out

**Comment by cinhcet** [comment]
I just tried it twice and for me it is always checked?!? Also if you look at the json file, the debug node has
`"active": true,
"tosidebar": true,`

Which version of node-red are you using?

**Comment by littleyoda** [comment]
you are right ... strange ...
