### ISSUE TITLE
can't bundle...

### ISSUE THREAD

**Issue by tve** [cinhcet/node-red-contrib-component-dashboard#4]
I'm running node-red in docker and I can't run the bundling. I have component-dashboard installed and the nodes show up in the node-red palette. I have a directory mounted on `/data` in the container and I created a config node, so now I have `/data/yad/yadtest`. The instructions state "you need to run `node bundle.js` in userDir/yad/yad" but that doesn't find node-red-contrib-component-dashboard and I'm not sure how it would...
```
tve@core /h/s/docker-node-red (master)> docker exec -ti docker-node-red.service /bin/bash
bash-5.0# cd /data/yad/yadtest/
bash-5.0# node bundle.js
⠋ Building.../bin/sh: lscpu: not found

> deasync@0.1.21 install /data/node_modules/deasync
> node ./build.js

make: Entering directory '/data/node_modules/deasync/build'
  CXX(target) Release/obj.target/deasync/src/deasync.o
  SOLINK_MODULE(target) Release/obj.target/deasync.node
  COPY Release/deasync.node
make: Leaving directory '/data/node_modules/deasync/build'
Installed in `/data/node_modules/deasync/bin/linux-arm-node-12/deasync.node`

> core-js@2.6.12 postinstall /data/node_modules/core-js
🚨  /data/yad/yadtest/main.js:2:16: Cannot find module 'node-red-contrib-component-dashboard' from '/data/yad/yadtest'
  1 | // main YAD library
> 2 | import YAD from 'node-red-contrib-component-dashboard/src/lib.js';
    |                ^
  3 |
  4 | // include widgets and css you want to use
  5 | import './widgets.js';
(node:150) UnhandledPromiseRejectionWarning: Error: Cannot find module 'node-red-contrib-component-dashboard' from '/data/yad/yadtest'
    at /usr/src/node-red/node_modules/resolve/lib/async.js:137:35
    at processDirs (/usr/src/node-red/node_modules/resolve/lib/async.js:290:39)
    at isdir (/usr/src/node-red/node_modules/resolve/lib/async.js:297:32)
    at /usr/src/node-red/node_modules/resolve/lib/async.js:25:69
    at FSReqCallback.oncomplete (fs.js:168:21)
(node:150) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async functio
n without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise re
jection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id:
 1)
(node:150) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled
will terminate the Node.js process with a non-zero exit code.
bash-5.0#
```

**Comment by cinhcet** [comment]
where is node-red-contrib-component-dashboard installed? Can you find it in /data/node_modules?

How are you mounting the /data folder? 
Do you have access to node.js outside of the docker? If yes, you could try to mount the data folder like so https://nodered.org/docs/getting-started/docker#using-a-host-directory-for-persistence-bind-mount and then run node bundle.js outside from the docker

**Comment by tve** [comment]
Thanks for the quick reply!
- `node-red-contrib-component-dashboard` is installed in the std node-red home dir in the container, i.e., `/usr/src/node-red/node_modules`
- the data dir is mounted as `-v some/dir/on/host:/data`, i.e., onto `/data` in the container (which is the std location and what you describe in your last sentence)
- I do not have node installed outside of the container (this is part of why I use a container, I'm running on a rPi-like arm box)

In a non-docker install does it work because the data dir is a subdir of the node-red dir and so there's only one `node_modules`?

**Comment by tve** [comment]
So I used docker exec to npm install component dashboard in `/data` as well, now node budle.js works but I'm stuck on the next issue, which is that requests to `host:1880/yad` return a 404...

update: I have the `httpStatic` config option set in nodered to /data/static  so it doesn't serve up the whole data directory... I had to move the yad directory under the data/static dir to get it to serve up, sort-of. I get the unstyled html without any actual widgets, so not really working at all. I suppose /yad is really supposed to be mounted differently, have to look...

**Comment by cinhcet** [comment]
The code is using its own serveStatic to serve the frontend files.

Just to make sure, /data is the userDir of node-red? And there is the folder /data/yad/NAMEOFYOURDASHBOARD/dist?

Can you maybe add before line https://github.com/cinhcet/node-red-contrib-component-dashboard/blob/master/nodes/yad.js#L74
the following
`console.log(path.join(node.yadFolder, "dist"));`
and post the output here?

**Comment by tve** [comment]
```
bash-5.0# ls /data/yad
yadtest
bash-5.0# ls /data/yad/yadtest/
bundle.js             dist                  index.html            manifest.webmanifest  widgets.js
createWidget.js       flows.json            main.js               style.css
bash-5.0# ls /data/yad/yadtest/dist
index.html            main.1f19ae8e.css     main.1f19ae8e.js      manifest.webmanifest
bash-5.0#
```
I'll try to add the console log but it's a bit involved 'cause I have to restart nodered after adding that line and there's no way to restart nodered without relaunching the container and that starts with the original module...

**Comment by cinhcet** [comment]
this looks all fine. So I guess that node.yadFolder is for some reason not /data/yad/yadtest
But let us see

**Comment by tve** [comment]
OK, so while trying to do the above, I noticed:
```
23 Mar 17:40:21 - [info] [yad-configuration:yadtest] YAD started at /yadtest
```
and indeed, the demo shows at `host:1880/yadtest`, i.e., no intervening `/yad/`...

**Comment by cinhcet** [comment]
ahh :-) 
Then everything is working, right?

You can make as many dashboards as you want. All are stored in the yad folder, but you access them by their name in the URL.

**Comment by tve** [comment]
I see the confusion, in the README your example is called "yad" and then you say "After bundling, the dashboard can be reached at http://127.0.0.1:1880/yad" where "yad" is the name of the example, not the "constant" yad. I thought there was a top /yad page... It would be more obvious if you named you first example "example1" or something like that...

**Comment by cinhcet** [comment]
I agree.
But at least the readme is consistent.

Maybe I can chance this if I do something else anyway.

Glad that it now also works in docker. You only had to install it manually in the /data folder, correct? That might also be worth mentioning in the readme.

Can we close?

**Comment by tve** [comment]
Yes, basically:
```
docker exec -ti <container_name> /bin/bash
cd /data
npm install cinhcet/node-red-contrib-component-dashboard
```
